### PR TITLE
Fix capsize style errors

### LINKED ISSUE #455: Latest version 1.0.0 fails to start
Version: `playroom@1.0.0`
Node: `v24.11.1`
Package manager: `pnpm@10.22.0`

Reproduction: https://github.com/pascalduez/playroom-repro

Trying to run the simplest setup possible fails with the following errors.

### Output
```sh
> playroom start

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9000/, http://[::1]:9000/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.21:9000/
<i> [webpack-dev-server] Content not from webpack is served from '/.../playroom-repro/public' directory
<i> [webpack-dev-middleware] wait until bundle finished: /
                                                    

 ERROR  Failed to compile with 2 errors                                                                                                                     
                                                                                                         
 error  in ./node_modules/.pnpm/playroom@1.0.0_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/playroom/src/components/Heading/Heading.css.ts
                                                                                                         
Syntax Error: Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:
                                                                                                         
- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
                                                    
                                                                                                         
 error  in ./node_modules/.pnpm/playroom@1.0.0_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/playroom/src/components/Text/Text.css.ts
                                                                                                         
Syntax Error: Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:
                                                                                                         
- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
```

### PR DESCRIPTION
**Pull request by askoufis**
Fixes #455.

v1 introduced a `@capsizecss/vanilla-extract` dependency. This package ships with its own VE styles that need to be handled by playroom's webpack configuration.

### CODE REVIEW

File: lib/makeWebpackConfig.js [hunk 1]
```diff
@@ -106,9 +108,12 @@ module.exports = async (playroomConfig, options) => {
...
           test: /\.vanilla\.css$/i,
-          include: playroomPath.includes('node_modules')
-            ? /node_modules\/playroom/
-            : undefined,
+          include:
+            // When playroom is inside `node_modules` ensure only playroom and capsize
+            // Vanilla Extract CSS modules are loaded by our webpack config.
+            playroomPath.includes('node_modules')
+              ? [/node_modules\/playroom/, /@capsizecss.vanilla-extract/]
+              : undefined,
```
Comment (askoufis) [inline lib/makeWebpackConfig.js]: Originally I tried this:

```suggestion
            [playroomPath.includes('node_modules')
              ? /node_modules\/playroom/
              : undefined,
            /@capsizecss.vanilla-extract/]
```

However that resulted in _only_ capsize styles being handled in the repo, so all the test fixtures broke. The new `include` array is more correct as we only care about `node_modules/playroom` and capsize styles when `playroom` itself is inside `node_modules`. In the playroom repo we can just load all VE CSS modules.

**Review by michaeltaranto — APPROVED** [review]
